### ISSUE TITLE
GKE node price is $0.00 with certain machine_types

### ISSUE THREAD

**Issue by b4nst** [infracost/infracost#2091] opened 2022-10-14 16:17 UTC
When running infracost against a GKE cluster, node and storage are set to "free".

```
 module.cluster_main.google_container_node_pool.node_pool["runners"]
 ├─ Instance usage (Linux/UNIX, preemptible, e2-highcpu-16)                                               10,950  hours                    $0.00
 └─ SSD provisioned storage (pd-ssd)                                                                       3,000  GB                       $0.00
```

**Comment by alikhajeh1** [comment] 2022-10-14 16:36
@b4nst thanks for reporting this issue! Can you please copy/paste the TF resource block that was used to generate this, as well as any warning lines from `infracost breakdown --log-level debug` so we can reproduce it and quickly fix it?

**Comment by b4nst** [comment] 2022-10-14 17:11
So I cannot share the whole config here but the node pools look like:

```terraform
resource "google_container_node_pool" "node_pool" {
  provider = google-beta
  for_each = var.node_pools

  name    = each.key
  cluster = google_container_cluster.cluster.id

  // Set the number of pods per node
  max_pods_per_node = each.value.max_pod_per_node == null ? var.default_max_pods_per_node : each.value.max_pod_per_node
  // Initial number of nodes to set on node pool creation
  initial_node_count = each.value.initial_node_count

  autoscaling {
    min_node_count = each.value.min_node_count
    max_node_count = each.value.max_node_count
  }

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  upgrade_settings {
    max_surge       = each.value.max_surge
    max_unavailable = 0
  }

  node_config {
    preemptible  = each.value.preemptible
    machine_type = each.value.machine_type
    image_type   = "COS_CONTAINERD"

    disk_size_gb = each.value.disk_size
    disk_type    = each.value.disk_type

    tags = [local.node_network_tag]

    workload_metadata_config {
      mode = "GKE_METADATA"
    }

    service_account = google_service_account.node_sa.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}
```

Regarding the warnings, I guess it explain the issue:

```
time="2022-10-14T19:09:06+02:00" level=warning file="<redacted>/infracost/work/gopath/src/github.com/infracost/infracost/internal/prices/prices.go:103" func=github.com/infracost/infracost/internal/prices.setCostComponentPrice msg="No products found for module.cluster_main.google_container_node_pool.node_pool[\"runners\"] Instance usage (Linux/UNIX, preemptible, e2-highcpu-16), using 0.00"
time="2022-10-14T19:09:06+02:00" level=warning file="<redacted>/infracost/work/gopath/src/github.com/infracost/infracost/internal/prices/prices.go:103" func=github.com/infracost/infracost/internal/prices.setCostComponentPrice msg="No products found for module.cluster_main.google_container_node_pool.node_pool[\"runners\"] SSD provisioned storage (pd-ssd), using 0.00"
time="2022-10-14T19:09:06+02:00" level=warning file="<redacted>/infracost/work/gopath/src/github.com/infracost/infracost/internal/prices/prices.go:103" func=github.com/infracost/infracost/internal/prices.setCostComponentPrice msg="No products found for module.cluster_main.google_container_node_pool.node_pool[\"core\"] Instance usage (Linux/UNIX, on-demand, e2-highcpu-4), using 0.00"
time="2022-10-14T19:09:06+02:00" level=warning file="<redacted>/infracost/work/gopath/src/github.com/infracost/infracost/internal/prices/prices.go:103" func=github.com/infracost/infracost/internal/prices.setCostComponentPrice msg="No products found for module.cluster_main.google_container_node_pool.node_pool[\"core\"] Standard provisioned storage (pd-standard), using 0.00"
```

**Comment by alikhajeh1** [comment] 2022-10-14 18:27
@b4nst perfect! That's very helpful. This looks like a pricing issue so we'll look at it, we usually see this when new regions are added and they've not been picked-up in our Cloud Pricing API yet, which region are you using?

**Comment by b4nst** [comment] 2022-10-15 10:19
I'm using `us-central1`

**Comment by tim775** [comment] 2022-10-16 14:47
@b4nst it looks like we do have prices for `Linux/UNIX, preemptible, e2-highcpu-16` in `us-central1`.  What version of the CLI are you using and are you using the self-hosted cloud pricing API?

**Comment by b4nst** [comment] 2022-10-16 19:31
I'm running the latest version (`v0.10.12`) and I'm using
```shell
❯ infracost configure get pricing_api_endpoint
https://pricing.api.infracost.io
```
which I think is the standard hosted version right?

**Comment by tim775** [comment] 2022-10-17 18:28
Yes that is the standard pricing api so that shouldn't be a problem.  We do have prices for preemptible e2-highcpu-16 in us-central1, so maybe the region isn't being picked up properly.  

Can you share the `google_container_cluster` config (at least the `location` param)?  It picks up the region from cluster if there is no `location` set directly on the `google_container_node_pool`.

Also, do you see any other warning logs?  I get this message if there is no `location` on the cluster or node pool:
```
time="2022-10-17T14:21:30-04:00" level=warning msg="Skipping resource google_container_node_pool.node_pool. Unable to determine region"
 ```

**Comment by aliscott** [comment] 2022-11-14 14:00
> Can you share the `google_container_cluster` config (at least the `location` param)? It picks up the region from cluster if there is no `location` set directly on the `google_container_node_pool`.
> 
> Also, do you see any other warning logs? I get this message if there is no `location` on the cluster or node pool:

Closing this issue since we've been unable to reproduce. @b4nst please re-open if you can provide the above information and we can investigate further 🙏 .

**Comment by infowolfe** [comment] 2023-02-17 17:16
I tried this with both a module and with everything jammed into `main.tf` and it's certainly reliably failing for me.

I presume this line has something to do with it, but who knows, infracost also doesn't seem to grok that I'm operating in `us-east1-b`: `{CloudEnabled:false ActualCostsEnabled:false UsageAPIEnabled:false}" msg="Successfully loaded settings from Infracost Cloud`

@aliscott just saying... closing an issue like this without actually investigating at all just makes for a bad user experience. The fact that this was closed more than 3 months ago now and is still a problem isn't a good look, especially when even the most basic example from https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/container_cluster results in failure if you so much as change the region or machine type.

```
time="2023-02-17T12:13:37-05:00" level=debug is_cloud_enabled=false msg="IsCloudEnabled inferred from Config.EnabledDashboard"
time="2023-02-17T12:13:37-05:00" level=debug msg="'POST' request to '/graphql' using trace_id: '48cf83a7-ced2-4adb-8120-6ff29e4d3b32'"
time="2023-02-17T12:13:37-05:00" level=debug result="{CloudEnabled:false ActualCostsEnabled:false UsageAPIEnabled:false}" msg="Successfully loaded settings from Infracost Cloud"
time="2023-02-17T12:13:37-05:00" level=debug msg="could not detect a specific CI system, fetching local Git metadata"
time="2023-02-17T12:13:37-05:00" level=debug error="could not open git directory to fetch metadata repository does not exist" msg="failed to fetch vcs metadata for path plan.json"
time="2023-02-17T12:13:37-05:00" level=info msg="Detected Terraform plan JSON file at plan.json"
time="2023-02-17T12:13:37-05:00" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2023-02-17T12:13:37-05:00" level=debug error="failed to detect a git directory in path plan.json of any of its parent dirs repository does not exist" msg="Could not get git top level directory for plan.json"
time="2023-02-17T12:13:37-05:00" level=debug is_cloud_enabled=false msg="IsCloudEnabled inferred from Config.EnabledDashboard"
time="2023-02-17T12:13:37-05:00" level=debug msg="Falling back to default region (us-central1) for google_container_cluster.primary"
time="2023-02-17T12:13:37-05:00" level=debug msg="Falling back to default region (us-central1) for google_container_node_pool.primary_preemptible_nodes"
time="2023-02-17T12:13:37-05:00" level=debug msg="Falling back to default region (us-central1) for google_service_account.default"
time="2023-02-17T12:13:37-05:00" level=debug msg="Loading usage data from Infracost provider resources"
time="2023-02-17T12:13:37-05:00" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2023-02-17T12:13:37-05:00" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for google_container_node_pool.primary_preemptible_nodes"
time="2023-02-17T12:13:37-05:00" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for google_container_cluster.primary"
time="2023-02-17T12:13:37-05:00" level=debug msg="'POST' request to '/graphql' using trace_id: '48cf83a7-ced2-4adb-8120-6ff29e4d3b32'"
time="2023-02-17T12:13:37-05:00" level=debug msg="'POST' request to '/graphql' using trace_id: '48cf83a7-ced2-4adb-8120-6ff29e4d3b32'"
time="2023-02-17T12:13:37-05:00" level=debug library=retryablehttp msg="performing request method POST url https://pricing.api.infracost.io/graphql"
time="2023-02-17T12:13:37-05:00" level=debug library=retryablehttp msg="performing request method POST url https://pricing.api.infracost.io/graphql"
time="2023-02-17T12:13:37-05:00" level=warning msg="No prices found for google_container_node_pool.primary_preemptible_nodes Instance usage (Linux/UNIX, on-demand, t2d-standard-16), using 0.00"
time="2023-02-17T12:13:37-05:00" level=debug msg="Skipping free resource google_service_account.default"
time="2023-02-17T12:13:37-05:00" level=debug is_cloud_enabled=false msg="IsCloudEnabled inferred from Config.EnabledDashboard"
time="2023-02-17T12:13:37-05:00" level=debug msg="Skipping sending project results since Infracost Cloud upload is not enabled."
time="2023-02-17T12:13:37-05:00" level=debug msg="'POST' request to '/event' using trace_id: '48cf83a7-ced2-4adb-8120-6ff29e4d3b32'"
time="2023-02-17T12:13:37-05:00" level=debug library=retryablehttp msg="performing request method POST url https://pricing.api.infracost.io/event"

Project: plan.json

 Name                                                        Monthly Qty  Unit   Monthly Cost 
                                                                                              
 google_container_cluster.primary                                                             
 └─ Cluster management fee                                           730  hours        $73.00 
                                                                                              
 google_container_node_pool.primary_preemptible_nodes                                         
 ├─ Instance usage (Linux/UNIX, on-demand, t2d-standard-16)        2,190  hours         $0.00 
 └─ Standard provisioned storage (pd-standard)                       300  GB           $12.00 
                                                                                              
 OVERALL TOTAL                                                                         $85.00 
──────────────────────────────────
3 cloud resources were detected:
∙ 2 were estimated, all of which include usage-based costs, see https://infracost.io/usage-file
∙ 1 was free:
  ∙ 1 x google_service_account
```

```
> infracost --version
Infracost v0.10.17
```

```main.tf
resource "google_service_account" "default" {
  account_id   = "service-account-id"
  display_name = "Service Account"
}

resource "google_container_cluster" "primary" {
  name     = "my-gke-cluster"
  location = "us-east1-b"

  # We can't create a cluster with no node pool defined, but we want to only use
  # separately managed node pools. So we create the smallest possible default
  # node pool and immediately delete it.
  remove_default_node_pool = true
  initial_node_count       = 3
}

resource "google_container_node_pool" "primary_preemptible_nodes" {
  name       = "my-node-pool"
  location   = "us-east1-b"
  cluster    = google_container_cluster.primary.name
  node_count = 3

  node_config {
    preemptible  = false
    machine_type = "t2d-standard-16"

    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.default.email
    oauth_scopes    = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }
}
```
lines changed from example: `location`, `node_count`, `machine_type`


running via:
```sh
#!/bin/bash

terraform plan -out tfplan.binary
terraform show -json tfplan.binary > plan.json
infracost breakdown --path plan.json --log-level trace --show-skipped
```

**Comment by hugorut** [comment] 2023-02-17 19:56
Hi @infowolfe, thanks for the additional steps to replicate. This seems like an issue with the filters sent to the cloud pricing API. I'm assuming that machine type might have a different product type than others. e.g. if I change the `machine_type` to `"n1-standard-16"` in your example we get a valid price. We'll look into this as soon as we can. As always @infowolfe, we welcome contributions.

**Comment by infowolfe** [comment] 2023-02-17 20:30
@hugorut I'm still seeing this:

```
time="2023-02-17T15:00:51-05:00" level=debug msg="Falling back to default region (us-central1) for google_container_cluster.primary"
time="2023-02-17T15:00:51-05:00" level=debug msg="Falling back to default region (us-central1) for google_container_node_pool.primary_preemptible_nodes"
time="2023-02-17T15:00:51-05:00" level=debug msg="Falling back to default region (us-central1) for google_service_account.default"
``` 

despite the fact that the region is set to `us-east1`. As for contributions, it seems that your [api is at fault](https://github.com/infracost/cloud-pricing-api/blob/master/src/scrapers/gcpMachineTypes.ts)

**Comment by hugorut** [comment] 2023-02-20 08:36
hi @infowolfe, thanks for the your contributions on the `cloud-pricing-api` side. The region message that you're seeing is a red herring. We are using the `us-east1` location attribute to fetch prices. This log line is coming from fetching the `region` from the provider block. So can be ignored, we should probably change the messaging so it doesn't confuse users in the future. Here's the actual graphql request that's being sent:

```
[
  {
    "query": "\n\t\tquery($productFilter: ProductFilter!, $priceFilter: PriceFilter) {\n\t\t\tproducts(filter: $productFilter) {\n\t\t\t\tprices(filter: $priceFilter) {\n\t\t\t\t\tpriceHash\n\t\t\t\t\tUSD\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t",
    "variables": {
      "priceFilter": {
        "purchaseOption": "on_demand"
      },
      "productFilter": {
        "vendorName": "gcp",
        "service": "Compute Engine",
        "productFamily": "Compute Instance",
        "region": "us-east1",
        "attributeFilters": [
          {
            "key": "machineType",
            "value_regex": "/^t2d-standard-16$/i"
          }
        ]
      }
    }
  },
  {
    "query": "\n\t\tquery($productFilter: ProductFilter!, $priceFilter: PriceFilter) {\n\t\t\tproducts(filter: $productFilter) {\n\t\t\t\tprices(filter: $priceFilter) {\n\t\t\t\t\tpriceHash\n\t\t\t\t\tUSD\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t",
    "variables": {
      "priceFilter": {
        "endUsageAmount": ""
      },
      "productFilter": {
        "vendorName": "gcp",
        "service": "Compute Engine",
        "productFamily": "Storage",
        "region": "us-east1",
        "attributeFilters": [
          {
            "key": "description",
            "value_regex": "/^Storage PD Capacity/"
          }
        ]
      }
    }
  }
]
```

as you can see we're using `us-east1`.

**Comment by hugorut** [comment] 2023-02-22 09:41
@infowolfe I'm closing this as your fix in the `cloud-pricing-api` seems to have resolved these missing prices. Thanks for your help.

**Closed by hugorut** 2023-02-22 09:41 UTC
Labels: bug, google, needs details
