### ISSUE TITLE
AWS ASG cost issues after ASG rebuild

### ISSUE THREAD

**Issue by adrianmiron** [infracost/infracost#2366] opened 2023-03-21 12:26 UTC
Hi,

The estimated cost on my ASG's has gone to max after i did an ASG recreate ( triggered by  lifecycle changes for aws termination handler ). I am unsure why it is estimating my ASG according to the maximum number of nodes right now , when the minimum is 0 .... 

New estimation :

```
{
            "name": "module.k8s.module.eks.module.self_managed_node_group[\"stable\"].aws_autoscaling_group.this[0]",
            "metadata": {
              "calls": [
                {
                  "blockName": "module.k8s",
                  "filename": "eks.tf"
                },
                {
                  "blockName": "module.eks",
                  "filename": ".infracost/terraform_modules/5f58cc43b9bde3843b851b9441caa558/eks.tf"
                },
                {
                  "blockName": "module.self_managed_node_group",
                  "filename": ".infracost/terraform_modules/898599a9b41926e2b661f7eeb7c7c912/node_groups.tf"
                },
                {
                  "blockName": "aws_autoscaling_group.this",
                  "filename": ".infracost/terraform_modules/898599a9b41926e2b661f7eeb7c7c912/modules/self-managed-node-group/main.tf"
                }
              ],
              "filename": ".infracost/terraform_modules/898599a9b41926e2b661f7eeb7c7c912/modules/self-managed-node-group/main.tf"
            },
            "hourlyCost": "9.12",
            "monthlyCost": "6657.6",
            "subresources": [
              {
                "name": "module.k8s.module.eks.module.self_managed_node_group[\"stable\"].aws_launch_template.this[0]",
                "metadata": {},
                "hourlyCost": "9.12",
                "monthlyCost": "6657.6",
                "costComponents": [
                  {
                    "name": "Instance usage (Linux/UNIX, on-demand, t3.xlarge)",
                    "unit": "hours",
                    "hourlyQuantity": "50",
                    "monthlyQuantity": "36500",
                    "price": "0.1824",
                    "hourlyCost": "9.12",
                    "monthlyCost": "6657.6"
                  },
                  {
                    "name": "EC2 detailed monitoring",
                    "unit": "metrics",
                    "hourlyQuantity": "0",
                    "monthlyQuantity": "0",
                    "price": "0.3",
                    "hourlyCost": "0",
                    "monthlyCost": "0"
                  },
                  {
                    "name": "CPU credits",
                    "unit": "vCPU-hours",
                    "hourlyQuantity": "0",
                    "monthlyQuantity": "0",
                    "price": "0.05",
                    "hourlyCost": "0",
                    "monthlyCost": "0"
                  }
                ],
                "subresources": [
                  {
                    "name": "block_device_mapping[0]",
                    "metadata": {},
                    "hourlyCost": "0",
                    "monthlyCost": "0",
                    "costComponents": [
                      {
                        "name": "Storage (general purpose SSD, gp3)",
                        "unit": "GB",
                        "hourlyQuantity": "0",
                        "monthlyQuantity": "0",
                        "price": "0.088",
                        "hourlyCost": "0",
                        "monthlyCost": "0"
                      }
                    ]
                  }
                ]
              }
            ]
          },
```

Old Estimation: 

```
{
            "name": "module.k8s.module.eks.module.self_managed_node_group[\"stable\"].aws_autoscaling_group.this[0]",
            "metadata": {
              "calls": [
                {
                  "blockName": "module.k8s",
                  "filename": "eks.tf"
                },
                {
                  "blockName": "module.eks",
                  "filename": ".infracost/terraform_modules/570d25f2dcd254535b56778849d1ecb8/eks.tf"
                },
                {
                  "blockName": "module.self_managed_node_group",
                  "filename": ".infracost/terraform_modules/c2143823945156c30cca218b595b5756/node_groups.tf"
                },
                {
                  "blockName": "aws_autoscaling_group.this",
                  "filename": ".infracost/terraform_modules/c2143823945156c30cca218b595b5756/modules/self-managed-node-group/main.tf"
                }
              ],
              "filename": ".infracost/terraform_modules/c2143823945156c30cca218b595b5756/modules/self-managed-node-group/main.tf"
            },
            "hourlyCost": null,
            "monthlyCost": null
          },
```

ASG terraform state :  ( nothing changed except the lifecycle and tag for aws-termination-handler) . Issue reproduced on two environments so far
```
  module.k8s.module.eks.module.self_managed_node_group["stable"].aws_autoscaling_group.this[0]:
resource "aws_autoscaling_group" "this" {
    arn                       = "----"
    availability_zones        = [
        "eu-west-1a",
        "eu-west-1b",
        "eu-west-1c",
    ]
    capacity_rebalance        = false
    default_cooldown          = 300
    default_instance_warmup   = 0
    desired_capacity          = 0
    enabled_metrics           = [
        "GroupDesiredCapacity",
        "GroupInServiceInstances",
        "GroupMaxSize",
        "GroupMinSize",
        "GroupPendingInstances",
        "GroupStandbyInstances",
        "GroupTerminatingInstances",
        "GroupTotalInstances",
    ]
    force_delete              = true
    force_delete_warm_pool    = false
    health_check_grace_period = 300
    health_check_type         = "EC2"
    id                        = "stable-20230321072037035700000004"
    load_balancers            = []
    max_instance_lifetime     = 0
    max_size                  = 50
    metrics_granularity       = "1Minute"
    min_size                  = 0
    name                      = "stable-20230321072037035700000004"
    name_prefix               = "stable-"
    protect_from_scale_in     = true
    service_linked_role_arn   = "*****"
    suspended_processes       = []
    target_group_arns         = []
    termination_policies      = []
    vpc_zone_identifier       = [
        -----
    ]
    wait_for_capacity_timeout = "10m"
    initial_lifecycle_hook {
        default_result          = "CONTINUE"
        heartbeat_timeout       = 300
        lifecycle_transition    = "autoscaling:EC2_INSTANCE_TERMINATING"
        name                    = "aws-termination-handler"
        notification_target_arn = "***"
        role_arn                = "----"
    }

    mixed_instances_policy {
        instances_distribution {
            on_demand_allocation_strategy            = "prioritized"
            on_demand_base_capacity                  = 50
            on_demand_percentage_above_base_capacity = 0
            spot_allocation_strategy                 = "lowest-price"
            spot_instance_pools                      = 2
        }

        launch_template {
            launch_template_specification {
                launch_template_id   = "lt-0d09738d451d1d5b1"
                launch_template_name = "stable-2022021414273370140000000a"
                version              = "21"
            }

            override {
                instance_type     = "t3.xlarge"
                weighted_capacity = "1"
            }
            override {
                instance_type     = "t3.large"
                weighted_capacity = "1"
            }
        }
    }

   
    tag {
        key                 = "ManagedBy"
        propagate_at_launch = true
        value               = "Terraform"
    }
  
    tag {
        key                 = "Owner"
        propagate_at_launch = true
        value               = "devops"
    }
    tag {
        key                 = "Team"
        propagate_at_launch = true
        value               = "devops"
    }
    tag {
        key                 = "aws-node-termination-handler/managed"
        propagate_at_launch = true
        value               = "true"
    }
    tag {
        key                 = "k8s.io/cluster-autoscaler/enabled"
        propagate_at_launch = true
        value               = "true"
    }
    tag {
        key                 = "k8s.io/cluster-autoscaler/node-template/label/nodegroup"
        propagate_at_launch = true
        value               = "stable"
    }
    tag {
        key                 = "k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage"
        propagate_at_launch = true
        value               = "100Gi"
    }
 
    timeouts {}
}
```

**Comment by vdmgolub** [comment] 2023-03-21 15:18
Hello! Thank you for creating the issue!

Could you please provide some code that helps us reproduce this issue? Also, can you tell if you use Infracost with Terraform's plan JSON or do you point it to the directory with the TF code?

**Comment by vdmgolub** [comment] 2023-03-22 12:00
@adrianmiron Looking at the state I think the count 50 comes from `on_demand_base_capacity` value in `mixed_instances_policy` block. The Infracost resource falls back to calculate the instance count using the launch template configuration because `desired_capacity` is 0.

I'm not sure though how the old estimate was calculated. Was it the exact same code or did anything change?

**Comment by adrianmiron** [comment] 2023-03-22 15:44
I will give it shot and update , thanks

**Comment by vdmgolub** [comment] 2023-03-23 12:27
I'm going to close this issue for now. Feel free to reopen if anything is still unclear. Thanks again for creating the issue! Hope you're enjoying using Infracost :)

**Closed by vdmgolub** 2023-03-23 12:27 UTC
