### ISSUE TITLE
Missing cost estimate for `azurerm_redis_cache`

### ISSUE THREAD

**Issue by mablanco** [infracost/infracost#1890] opened 2022-07-22 08:27 UTC
Hi there. The breakdown for `azurerm_redis_cache` doesn't seem to work, as it reports $0.00 for all tiers and SKU names I've tested (quite a good amount of them). I tested various linux-based infracost versions from 0.10.x (including 0.10.8) branch to no avail. Be aware that the Redis resources were added in the 0.10.x branch.

Current output:
```
azurerm_redis_cache.main
 └─ Cache usage (Premium_C6, 2 nodes)                                       1,460  hours                            $0.00
```
I can provide more info if needed/requested. Thanks!

**Comment by hugorut** [comment] 2022-07-22 08:40
Thanks @mablanco this seems like a configuration issue. Premium nodes can only use `P` for the family type. See the `azurerm_redis_cache` docs [here]( https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache) that state:

> [family](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redis_cache#family) - (Required) The SKU family/pricing group to use. Valid values are C (for Basic/Standard SKU family) and P (for Premium)

This is inline with the [azure pricing page](https://azure.microsoft.com/en-gb/pricing/details/cache/) which only shows pricing for premium cache for names `P1` - `P5`

So if you change the `family` attribute to `P` and `capacity` to a number under 5. You'll get a valid price output. e.g:

```
resource "azurerm_redis_cache" "premium_p1" {
  name                = "example-cache"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  capacity            = 4
  family              = "P"
  sku_name            = "Premium"
  shard_count         = 1
}
```

```
 azurerm_redis_cache.premium_p1
 └─ Cache usage (Premium_P4, 2 nodes)                                 1,460  hours                          $6,482.40
```

I'm closing this issue as this is not a bug with Infracost, but a Terraform configuration issue.

**Closed by hugorut** 2022-07-22 08:40 UTC
Labels: bug, needs details

**Comment by mablanco** [comment] 2022-07-22 09:09
Yes, you're completely right. The thing is that I was quite sure I had tested several combinations that failed before opening the issue. Thanks for clarifying and sorry for taking your time. Good job!
