### ISSUE TITLE
Terraform resources with count=0 appear in the costs

### ISSUE THREAD

**Issue by oliver-sentianse** [infracost/infracost#1968] opened 2022-08-12 16:41 UTC
Awesome tool and presentation. 

BUT we noticed a cost breakdown error when we were trying it out today, so with today's version as installed per your instructions using curl. 

We have 2 terraform-managed stacks based on the same underlying terraform code, one stack has count=0 for the redshift DB, the other has count=1. I checked with `terraform state list` that redshift is only in the stack with count=1. Yet `infracost breakdown --path=.` in each folder reports redshift cost even for stack where count=0. Since redshift is almost 90% of the cost of that stack, it is major issue for us. 
```
$ infracost --version
Infracost v0.10.9
$ terraform version
Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.23.0
...
```

I really hope this can be fixed so we can use infracost!

**Comment by tim775** [comment] 2022-08-12 17:33
Hi @oliver-dss, thanks for the issue!  

I checked that `count = 0` is working at least in simple cases.  Could you share a sanitized version of the terraform code that causes the problem?  There are some simple [redshift examples here](https://github.com/infracost/infracost/blob/master/internal/providers/terraform/aws/testdata/redshift_cluster_test/redshift_cluster_test.tf) if you prefer to start from scratch. 

It also can be helpful if you run with `--log-level debug` and share the output.

Cheers

**Comment by schollii** [comment] 2022-08-12 18:03
Ah good to know. I'm sure it's nothing to do with redshift specifically, it was just obvious in that particular case. 

I suspect it is because the `count` is set from json loaded via `jsondecode(file(...))`. 

I might be afk for next days so if you don't get to try the above sooner, I'll try to pare down my stack and post the code when I get back. 

Thanks for a quick reply!

**Comment by oliver-dss** [comment] 2022-08-12 19:31
So this is super weird: I was able to pare it down to just one small .tf file and a .json file, and I could see the error. Then I added a couple more cases, one using a json string hardcoded and another using a variable with default value, and indeed those 2 were good. Then the error on the file case was gone. I commented out the 2 extra cases and the error is gone. 

My code was this: 
```
variable "tfvars_count" {
  type = number
  default = 0
}

locals {
  json_str = jsondecode("{\"count\": 0}")
  json_file = jsondecode(file("test.json"))
}

resource "aws_redshift_cluster" "test_from_str" {
  count = local.json_str.count

  cluster_identifier = "test_from_str"
  node_type = "dc2.large"
}

resource "aws_redshift_cluster" "test_from_json_file" {
  count = local.json_file.count

  cluster_identifier = "test_from_json_file"
  node_type = "dc2.large"
}

resource "aws_redshift_cluster" "test_from_tfvars" {
  count = var.tfvars_count

  cluster_identifier = "test_from_tfvars"
  node_type = "dc2.large"
}
```
and the `test.json`: 
```
{
  "count": 0
}
```

Semi-unfortunately the output has been correct with the above now for a few minutes ($0), whereas 15 min ago the earlier version of the file (which only had the one test based on test.json) had incorrect output:
```
$ infracost breakdown --path .
Evaluating Terraform directory at .
  ✔ Downloading Terraform modules 
  ✔ Evaluating Terraform directory 
  ✔ Retrieving cloud prices to calculate costs 

Estimate uploaded to organization 'oliver' in Infracost Cloud
Project: project_4lve5hje

 Name                                            Monthly Qty  Unit                      Monthly Cost 
                                                                                                     
 aws_redshift_cluster.test[0]                                                                        
 ├─ Cluster usage (on-demand, dc2.large)                 730  hours                          $182.50 
 ├─ Concurrency scaling (dc2.large)       Monthly cost depends on usage: $0.00007 per node-seconds   
 ├─ Spectrum                              Monthly cost depends on usage: $5.00 per TB                
 └─ Backup storage (first 50 TB)          Monthly cost depends on usage: $0.023 per GB               
                                                                                                     
 OVERALL TOTAL                                                                               $182.50 
──────────────────────────────────
1 cloud resource was detected:
∙ 1 was estimated, it includes usage-based costs, see https://infracost.io/usage-file
```

I tried deleting the `.infracost` folder AND the project created in `infracost.io` and then re-running, but to no avail, I am no longer able to see that bug. 

Could it be that you have some old containers running and some new ones, and only the older ones have the issue and now just by luck I'm hitting only the new ones? Or you just fixed the bug a few minutes ago!! :)

**Comment by tim775** [comment] 2022-08-12 20:46
This is awesome thanks for the effort!  I've come up with a couple test cases which may be related.  It looks like we're somehow defaulting to a value of 1 if we can't read the local properly:

```
locals {
  json_file = jsondecode(file("test.json"))
  missing_file = jsondecode(file("no.actual.file"))
  not_a_map = "some string, not a map"
}

resource "aws_redshift_cluster" "test_from_json_file" {
  count = local.json_file.not_a_real_key_in_the_json

  cluster_identifier = "test-from-json-file"
  node_type = "dc2.large"
}

resource "aws_redshift_cluster" "test_from_missing_file" {
  count = local.missing_file.count

  cluster_identifier = "test-from-missing-file"
  node_type = "dc2.large"
}

resource "aws_redshift_cluster" "test_from_not_a_map" {
  count = local.not_a_map.count

  cluster_identifier = "test-from-not-a-map"
  node_type = "dc2.large"
}
```

This doesn't explain your issue since it doesn't explain why we can't read the local inside that module, but they're still good bugs :).

**Comment by schollii** [comment] 2022-08-12 20:51
(I submitted this while logged into github from a business account, now signed in correctly)

Yes I noticed that when `terraform validate` does not pass on something that affects count, the count is 1.

**Comment by KyleKotowick** [comment] 2022-08-13 19:04
@oliver-dss I think you're passing the input variable incorrectly:
```
  maps = [local.json_file]
```

The `maps` input variable is supposed to be a list of maps that should be merged. If you are giving it an input list with only one element (the map that is in `json_file`), the output should be identical to the input, and this module serves no purpose.

If `json_file` is itself a list of maps, you'd want to use it like this:
```
  maps = local.json_file
```

Quickly browsing this issue, I'm not seeing what the actual error is, or what the unexpected output is. If the above recommendation doesn't fix the issue, please provide the contents of `local.json_file` and what you expect the output to be, so I can reproduce locally and compare.

**Comment by schollii** [comment] 2022-08-15 02:25
@KyleKotowick if the `maps` list has just one item (ie one map), then `module.defaults.merged` is identical to `local.json_file` (as it should), so there is no error there. Verification, by adding an output called `defaulst` for  `module.defaults.merged`: 
```
$ terraform plan

Changes to Outputs:
  + defaults = {
      + test = null
    }
```
This is to be expected since "merging" on a list of one map should produce that map! The code I have is not the actual code I use, just pared down version o fit that demonstrates the issue.

**Comment by KyleKotowick** [comment] 2022-08-15 21:54
> This file shows 3 cases, the first 2 confirm what @tim775 said about `count`. The 3rd case fails.

What does "fails" mean in this case? That infracost is reporting a cost for it even though the `count` should equal `0`, or that Terraform is actually throwing an error?

**Comment by aliscott** [comment] 2022-08-17 14:04
The current behavior for Infracost when we can't determine the count is to default to count=1. This is the case if the count is derived from a data resource, which we can't retrieve the value of by parsing the HCL.

However, this case looks different since it's not using any data resources.  From an initial glance it looks like all the information is there so we cab evaluate it to count=0 for the third case instead of defaulting to count=1. So this looks like it's  a bug in Infracost's HCL parsing that isn't handling some of the logic in the third-party deepmerge module correctly.

**Comment by schollii** [comment] 2022-08-17 21:48
Yes that's exactly what I figure.

**Comment by KyleKotowick** [comment] 2022-08-17 22:27
I'm going to unsubscribe from this since it seems like my module is working as expected. Feel free to @ me if it you find a bug with the deepmerge module.

**Comment by schollii** [comment] 2022-08-18 02:06
Sounds good @KyleKotowick, thanks for having a look

**Closed** 2022-12-07 17:21 UTC
Labels: bug

**Comment by hugorut** [comment] 2022-12-07 17:22
Thanks @oliver-sentianse for bringing this to our attention, a fix for this has been merged into master and will go out with the next release

**Comment by schollii** [comment] 2022-12-07 17:37
Thanks @hugorut!
