### ISSUE TITLE
Cost calculation differ between remote state and plan based calculation

### ISSUE THREAD

**Issue by dawidmalina** [infracost/infracost#349] opened 2021-01-21 08:28 UTC
I am prototyping infracost and I have faced strange issue. For some unknown reasons cost calculation are different between those two calculations:
- `infracost --no-color --tfdir . --tfplan ${PLAN}`
- `infracost --no-color --tfdir . --use-tfstate`

Terraform plan is empty:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.
```

Diff between calculations:
```
11c11 
<   ├ Transit gateway attachment                                                              730  hours        0.0500       0.0500       36.5000    
---
>   ├ Transit gateway attachment                                                              730  hours        0.0600       0.0600       43.8000    
13c13
<   Total                                                                                                                     0.0500       36.5000   
---
>   Total                                                                                                                     0.0600       43.8000   
45c45
<   OVERALL TOTAL (USD)                                                                                                       0.1940      141.6200  
---
>   OVERALL TOTAL (USD)                                                                                                       0.2040      148.9200   
```

**Comment by aliscott** [comment] 2021-01-21 08:41
@dawidmalina thanks. This looks like it's detecting the wrong region for some reason. Do you have an example of the Terraform file you are using for this?

**Comment by dawidmalina** [comment] 2021-01-21 08:44
It is working environment but i will try to provide code example soon.

**Comment by dawidmalina** [comment] 2021-01-21 09:49
Additional input. I am using here nasted modules (maybe this will help)
```
.
├── emea (dedicated provider)
│   └── main.tf -> use vpc module
└── noram (dedicated provider)
    └── main.tf -> here i don't use vpc module
```

The module defines this tgw attachment like this:
```
resource "aws_ec2_transit_gateway_vpc_attachment" "vpc_vc01" {
  count              = var.tgw_id == null ? 0 : 1
  subnet_ids         = aws_subnet.vpc_vc01.*.id
  transit_gateway_id = var.tgw_id
  vpc_id             = aws_vpc.vpc_vc01.id

  tags =var.tags
}
```

**Comment by aliscott** [comment] 2021-01-21 10:06
I'm wondering if it's hitting this issue: https://github.com/infracost/infracost/blob/master/internal/providers/terraform/parser.go#L193-L195

Can you run with `INFRACOST_LOG_LEVEL=debug` and see it if it outputs "Falling back to default region"?

If you have an example of how the AWS region is passed into your modules that would be useful as well.

**Comment by dawidmalina** [comment] 2021-01-21 11:56
```
infracost --log-level debug --no-color --tfdir . --tfplan ${PLAN}
```
```
time="2021-01-21T11:50:10Z" level=debug msg="Loading usage data from Infracost provider resources"
time="2021-01-21T11:50:10Z" level=info msg="starting: Calculating cost estimate"
time="2021-01-21T11:50:10Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]"
time="2021-01-21T11:50:10Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2_ep01[0]"
time="2021-01-21T11:50:10Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssm_ep01[0]"
time="2021-01-21T11:50:10Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2messages_ep01[0]"
time="2021-01-21T11:50:11Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssmmessages_ep01[0]"
time="2021-01-21T11:50:11Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_secretsmanager_ep01[0]"
time="2021-01-21T11:50:11Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.backup_notification.aws_sns_topic.main"
time="2021-01-21T11:50:11Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.sns[0]"
time="2021-01-21T11:50:11Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.alerts_notification.aws_sns_topic.main"
```

**Comment by dawidmalina** [comment] 2021-01-21 11:56
```
infracost --log-level debug --no-color --tfdir . --use-tfstate
```
```
time="2021-01-21T11:42:36Z" level=debug msg="Loading usage data from Infracost provider resources"
time="2021-01-21T11:42:36Z" level=info msg="starting: Calculating cost estimate"
time="2021-01-21T11:42:36Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2_ep01[0]"
time="2021-01-21T11:42:36Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2messages_ep01[0]"
time="2021-01-21T11:42:37Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssm_ep01[0]"
time="2021-01-21T11:42:37Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]"
time="2021-01-21T11:42:37Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.alerts_notification.aws_sns_topic.main"
time="2021-01-21T11:42:37Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssmmessages_ep01[0]"
time="2021-01-21T11:42:37Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.sns[0]"
time="2021-01-21T11:42:38Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_secretsmanager_ep01[0]"
time="2021-01-21T11:42:38Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.backup_notification.aws_sns_topic.main"
time="2021-01-21T11:42:38Z" level=info msg="starting: Running terraform show"
time="2021-01-21T11:42:38Z" level=info msg="Running command: /usr/bin/terraform show -no-color -json"
[redacted]
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Falling back to default region (us-east-1) for "
time="2021-01-21T11:42:44Z" level=debug msg="Loading usage data from Infracost provider resources"
time="2021-01-21T11:42:44Z" level=info msg="starting: Calculating cost estimate"
time="2021-01-21T11:42:44Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.alerts_notification.aws_sns_topic.main"
time="2021-01-21T11:42:44Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2_ep01[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ec2messages_ep01[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_secretsmanager_ep01[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssm_ep01[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.sns[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.vpc_ft_vc01.aws_vpc_endpoint.vpc_ssmmessages_ep01[0]"
time="2021-01-21T11:42:45Z" level=debug msg="Getting pricing details from https://pricing.api.infracost.io for module.emea.module.backup_notification.aws_sns_topic.main"
```

**Comment by dawidmalina** [comment] 2021-02-17 22:43
@aliscott i still see this issue with latest TF 0.14.7 and Infracost 0.7.20:
```diff
   module.apac.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]                                                                     
-  ├─ Transit gateway attachment                                                                   730  hours         0.0700       0.0700       51.1000  
+  ├─ Transit gateway attachment                                                                   730  hours         0.0600       0.0600       43.8000  
   └─ Data processed                                                                                 -  GB            0.0200            -             -  
-  Total                                                                                                                           0.0700       51.1000  
+  Total                                                                                                                           0.0600       43.8000  
```

In the output i see:
```
time="2021-02-17T22:28:17Z" level=debug msg="Falling back to default region (us-east-1) for module.apac.module.vpc_ft_vc01.aws_ec2_transit_gateway_vpc_attachment.vpc_vc01[0]"
```

**Comment by aliscott** [comment] 2021-02-18 12:00
Thanks @dawidmalina. I've been digging into this a bit.
So the issue is that the AWS API don't return an ARN or region from the AWS API for the VPC attachments so we have to get it from the Transit Gateway itself.

I see you're passing the `var.tgw_id` to the `aws_ec2_transit_gateway_vpc_attachment`. Are you defining the `aws_ec2_transit_gateway` anywhere in the Terraform code?

**Comment by dawidmalina** [comment] 2021-02-18 16:08
It's consumed as an output from different state in the network account

**Comment by aliscott** [comment] 2021-02-19 13:08
@dawidmalina good idea! I've added this here: https://github.com/infracost/infracost/pull/454.

**Comment by dawidmalina** [comment] 2021-03-04 13:40
@aliscott I found today new similar issue with ecs (fargate in this case) - no changes in the terraform

```
   module.noram.module.deployment.aws_ecs_service.this                                                                                                                
-  ├─ Per GB per hour                                                                                              0  GB-hours     0.0044       0.0000        0.0000  
-  └─ Per vCPU per hour                                                                                            0  CPU-hours    0.0405       0.0000        0.0000  
-  Total                                                                                                                                        0.0000        0.0000  
+  ├─ Per GB per hour                                                                                            730  GB-hours     0.0051       0.0051        3.7303  
+  └─ Per vCPU per hour                                                                                          365  CPU-hours    0.0466       0.0233       16.9944  
+  Total                                                                                                                                        0.0284       20.7247  
```

**Comment by aliscott** [comment] 2021-03-08 21:45
@dawidmalina thank you! https://github.com/infracost/infracost/pull/497 has a fix for this.

**Comment by dawidmalina** [comment] 2021-03-10 16:33
Another one usecase:
```
  module.apac.module.dx_secondary.aws_dx_gateway_association.dx[0]                                                                                                          
  ├─ Data processed                                                                                                    Cost depends on usage: $0.02 per GB                  
- └─ Transit gateway attachment                                                                                                     730  hours                       $36.50 
+ └─ Transit gateway attachment                                                                                                     730  hours                       $43.80 
```

**Closed** 2021-03-14 07:36 UTC
