### ISSUE TITLE
Support Cloud Formation templates & create cost estimates

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#352] opened 2021-01-22 13:14 UTC
Add support for Cloud Formation Templates. This is for users who are not using Terraform (or not only using terraform).

https://aws.amazon.com/cloudformation/

**Comment by alikhajeh1** [comment] 2021-01-22 18:18
This is a duplicate of https://github.com/infracost/infracost/issues/190

**Closed by alikhajeh1** 2021-01-22 18:18 UTC
