### ISSUE TITLE
v0.10.0 - infracost estimates wrong aws_eks_node_group instance billing type 

### ISSUE THREAD

**Issue by m00lecule** [infracost/infracost#1698] opened 2022-05-31 14:48 UTC
Hello! I would like to kindly report that infracost `v0.10.0` might badly estimate `aws_eks_node_group` that has dependency on `aws_launch_template`. 

Also I want to kindly ask for an enhancement: display `aws_launch_template` estimation as multiplication for example `number_of_instances * each_ec2_cost = cost`. Currently it might misslead somebody non technical that each EC2 costs monthly 2K $.

```console
$ infracost --version                                                   
Infracost v0.10.0
```

Proof:
![image](https://user-images.githubusercontent.com/33501567/171201882-67d76b6f-7cd7-4a1f-8f2c-4cef852d7cbc.png)

Reproduce

```console
$ terraform --version                                     
Terraform v0.14.11

Your version of Terraform is out of date! The latest version
is 1.2.1. You can update by downloading from https://www.terraform.io/downloads.html
$ terragrunt --version
[INFO] Getting version from tgenv-version-name
[INFO] TGENV_VERSION is 0.36.1
terragrunt version v0.36.1

$ infracost breakdown --path . --terraform-force-cli
```

**Comment by hugorut** [comment] 2022-05-31 14:52
Hey @m00lecule , thanks for reporting this. Could you give us a bit more information to help us understand this? What were you expecting to see here?

**Comment by hugorut** [comment] 2022-05-31 14:57
> Also I want to kindly ask for an enhancement: display aws_launch_template estimation as multiplication for example number_of_instances * each_ec2_cost = cost

This is what we actually do but we display it in the billable unit of hours. So in your case, it looks like you're running **11** instances (8030/730). We are thinking about changing these units to something slightly more readable. i.e. a number of instances.

**Comment by m00lecule** [comment] 2022-05-31 14:58
> > Also I want to kindly ask for an enhancement: display aws_launch_template estimation as multiplication for example number_of_instances * each_ec2_cost = cost
> 
> This is what we actually do but we display it in the billable unit of hours. So in your case, it looks like you're running **11** instances (8030/730). We are thinking about changing these units to something slightly more readable. i.e. a number of instances.

I would be pleased!

**Comment by alikhajeh1** [comment] 2022-06-14 19:52
@m00lecule any update on this?

**Comment by hugorut** [comment] 2022-07-20 14:14
Hey @m00lecule, any chance you could try the latest release [v0.10.8](https://github.com/infracost/infracost/releases/tag/v0.10.8) and see if this resolves your issue. We've made lots of improvements to the HCL parsing layer, and I'm hoping we could get some more info from you running this. If it fails, could you try running Infracost with the `--debug-report` flag and uploading the debug file here so we can dig in further?

**Comment by alikhajeh1** [comment] 2022-08-24 17:13
I'm going to close this issue as we can't reproduce it yet, please re-open it if you get a chance to debug further (sending us the "infracost-debug-report.json" file that `--debug-report` saves too please!).

**Closed by alikhajeh1** 2022-08-24 17:13 UTC
Labels: bug
