### ISSUE TITLE
Add package manager support for windoz users with chocolatey:

### ISSUE THREAD

**Issue by JamesWoolfenden** [infracost/infracost#799] opened 2021-06-09 16:27 UTC
Add package manager support for windoz users with chocolatey: 
like here: https://github.com/bridgecrewio/yor-choco

**Comment by aliscott** [comment] 2021-06-09 16:37
Duplicate of https://github.com/infracost/infracost/issues/798

**Closed by aliscott** 2021-06-09 16:37 UTC
