### ISSUE TITLE
Terragrunt project fails with --terraform-parse-hcl

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1658] opened 2022-05-13 21:32 UTC
Testing v0.9.24 with @dyordsabuzo showed this error, whilst I think one issue is that the Infracost error message isn't friendly, I'm not sure if this the root cause of the error. Infracost's `--terraform-parse-hcl` option should work with the top-level Terragrunt directory.

```
$ git clone https://github.com/dyordsabuzo/working-with-aws-ecs

$ cd  working-with-aws-ecs

$ infracost breakdown --path . --terraform-parse-hcl
Detected Terragrunt directory (HCL) at .

Error: 4 errors occurred:
	* Cannot process module Module /Users/ali/src/working-with-aws-ecs/asg (excluded: false, assume applied: false, dependencies: [/Users/ali/src/working-with-aws-ecs/ecs]) because one of its dependencies, Module /Users/ali/src/working-with-aws-ecs/ecs (excluded: false, assume applied: false, dependencies: [/Users/ali/src/working-with-aws-ecs/lb, /Users/ali/src/working-with-aws-ecs/db]), finished with an error: Cannot process module Module /Users/ali/src/working-with-aws-ecs/ecs (excluded: false, assume applied: false, dependencies: [/Users/ali/src/working-with-aws-ecs/lb, /Users/ali/src/working-with-aws-ecs/db]) because one of its dependencies, Module /Users/ali/src/working-with-aws-ecs/lb (excluded: false, assume applied: false, dependencies: []), finished with an error: error downloading 'tfr://app.terraform.io/pablosspot/pablosspot-lb/aws?version=0.0.1': Error downloading module from https://app.terraform.io/api/registry/v1/modules/pablosspot/pablosspot-lb/aws/0.0.1/download: error receiving HTTP data
	* error downloading 'tfr://app.terraform.io/pablosspot/pablosspot-rds/aws?version=0.0.7': Error downloading module from https://app.terraform.io/api/registry/v1/modules/pablosspot/pablosspot-rds/aws/0.0.7/download: error receiving HTTP data
	* Cannot process module Module /Users/ali/src/working-with-aws-ecs/ecs (excluded: false, assume applied: false, dependencies: [/Users/ali/src/working-with-aws-ecs/lb, /Users/ali/src/working-with-aws-ecs/db]) because one of its dependencies, Module /Users/ali/src/working-with-aws-ecs/lb (excluded: false, assume applied: false, dependencies: []), finished with an error: error downloading 'tfr://app.terraform.io/pablosspot/pablosspot-lb/aws?version=0.0.1': Error downloading module from https://app.terraform.io/api/registry/v1/modules/pablosspot/pablosspot-lb/aws/0.0.1/download: error receiving HTTP data
	* error downloading 'tfr://app.terraform.io/pablosspot/pablosspot-lb/aws?version=0.0.1': Error downloading module from https://app.terraform.io/api/registry/v1/modules/pablosspot/pablosspot-lb/aws/0.0.1/download: error receiving HTTP data
	* 
```

**Comment by aliscott** [comment] 2022-05-16 12:52
These errors are coming from the Terragrunt libraries we are using internally for the HCL parsing. We should probably and a note to the error to clarify that these are coming from there.

For this specific error it looks like it's failing to download a third party module. I get the same error on this project if I run `terragrunt run-all init` or `terragrunt run-all plan`, so I'm not sure if this is one we can fix or not.

**Comment by dyordsabuzo** [comment] 2022-05-16 21:25
I might have found the problem but i need to try it out on a clean clone of the repo.  I am using terraform cloud so i need to set the appropriate environment variable to pull in the modules.  I’ll give this a run later today and post an update here.

**Comment by dyordsabuzo** [comment] 2022-05-17 06:06
This s a rundown of what I did and unfortunately the `--terraform-parse-hcl` did not work.

1. cloned the repo https://github.com/dyordsabuzo/working-with-aws-ecs.git
2. ran `infracost breakdown --path . --terraform-parse-hcl` and got these error
```
* Cannot process module Module /tmp/working-with-aws-ecs/asg (excluded: false, assume applied: false, dependencies: [/tmp/working-with-aws-ecs/ecs]) because one of its dependencies, Module /tmp/working-with-aws-ecs/ecs (excluded: false, assume applied: false, dependencies: [/tmp/working-with-aws-ecs/lb, /tmp/working-with-aws-ecs/db]), finished with an error: /tmp/working-with-aws-ecs/ecs/terragrunt.hcl:35,46-63: Unsupported attribute; This object does not have an attribute named "target_group_arn"., and 4 other diagnostic(s)
        * /tmp/working-with-aws-ecs/ecs/terragrunt.hcl:35,46-63: Unsupported attribute; This object does not have an attribute named "target_group_arn"., and 4 other diagnostic(s)
```
3. ran `infracost breakdown --path .` without `--terraform-parse-hcl` and got the following error:
```
    │ Error: Failed to load state: default workspace not supported
    │ You can create a new workspace with the "workspace new" command.
```
And so I set my environment variable TF_WORKSPACE.

4. After exporting TF_WORKSPACE, i reran same command as step 2 and got exactly the same error.
5. I tried without `--terraform-parse-hcl` and got the following error
```
    * error downloading 'tfr://app.terraform.io/pablosspot/pablosspot-lb/aws?version=0.0.1': Error downloading module from https://app.terraform.io/api/registry/v1/modules/pablosspot/pablosspot-lb/aws/0.0.1/download: error recieving HTTP data
``` 
which seems to suggest that my session does not have permission to go to terraform cloud.  And so I exported an environment variable called `TG_TF_REGISTRY_TOKEN`.
6. I tried rerunning step 2, no dice, same error.
7. I tried without `--terraform-parse-hcl` and got the following error:
```
    Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.
    Error: NoCredentialProviders: no valid providers in chain
    caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
    SharedCredsLoad: failed to load profile, .
    EC2RoleRequestError: no EC2 instance role found
    caused by: RequestError: send request failed
    caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: no route to host       
      with provider["registry.terraform.io/hashicorp/aws"],
      on providers.tf line 1, in provider "aws":
       1: provider "aws" {
    time=2022-05-17T15:55:31+10:00 level=error msg=Module /tmp/working-with-aws-ecs/lb has finished with an error: 1 error occurred:
    * exit status 1
     prefix=[/tmp/working-with-aws-ecs/lb]
```
and so i exported my aws environment variables.

8.  Tried step 2, still same error
9. Tried without `--terraform-parse-hcl` and I got the result of the infracost breakdown.

**Comment by aliscott** [comment] 2022-05-17 16:22
Thanks for the detailed steps @dyordsabuzo. I think we should be able to reproduce with these steps now. I'll keep digging into it and keep you updated.

**Comment by aliscott** [comment] 2022-05-18 08:17
@dyordsabuzo I'm only able to reproduce this with a private module without the `TG_TF_REGISTRY_TOKEN` env var set.

With the following HCL code:
```hcl
terraform {
  source = "tfr://app.terraform.io/infracost/ec2-instance/aws?version=2.16.0"
}

inputs = {
  name           = "my-cluster"
  instance_count = 5

  ami                    = "ami-ebd02392"
  instance_type          = "t2.micro"
  key_name               = "user1"
  monitoring             = true
  vpc_security_group_ids = ["sg-12345678"]
  subnet_id              = "subnet-eddcdzz4"
}
```

And running:
```
make run -s ARGS="breakdown --path examples/terragrunt --terraform-parse-hcl"
```

I get:
```
Error: 1 error occurred:
	* error downloading 'tfr://app.terraform.io/infracost/ec2-instance/aws?version=2.16.0': Error downloading module from https://app.terraform.io/api/registry/v1/modules/infracost/ec2-instance/aws/2.16.0/download: error receiving HTTP data
```

But If I run:
```
export TG_TF_REGISTRY_TOKEN=<MY TFC TOKEN>
make run -s ARGS="breakdown --path examples/terragrunt --terraform-parse-hcl"
```

I get the expected output of:
```
Project: infracost/infracost/examples/terragrunt

 Name                                                 Monthly Qty  Unit     Monthly Cost

 aws_instance.this[0]
 ├─ Instance usage (Linux/UNIX, on-demand, t2.micro)          730  hours           $8.47
 ├─ EC2 detailed monitoring                                     7  metrics         $2.10
 └─ root_block_device
    └─ Storage (general purpose SSD, gp2)                       8  GB              $0.80

 OVERALL TOTAL                                                                    $11.37
```

Can you confirm this is still failing for you with the variable exported? If so are you able to run with `--log-level=debug`?

**Comment by dyordsabuzo** [comment] 2022-05-18 21:57
I turned on debug but there was nothing much in the result.

I may have found what the issue is.  It looks like the infracost run does not take into account the dependency block inside the terragrunt configuration file: `This object does not have an attribute named "target_group_arn"`.  And when I checked what's assigned to the variable, I pull the value from a dependency block.  As soon as I changed that to a string just to see what happens, that specific error went away and moved on to the next variable that pulls its value from the dependency block.

**Comment by aliscott** [comment] 2022-05-21 16:50
Thanks @dyordsabuzo. Looks like this is a similar issue to https://github.com/infracost/infracost/issues/1658.

**Comment by dyordsabuzo** [comment] 2022-05-21 22:14
> Thanks @dyordsabuzo. Looks like this is a similar issue to #1658.

You may have the incorrect bug reference number 😁 .  This is issue #1658

**Comment by aliscott** [comment] 2022-05-22 14:04
Oops, sorry I meant #1641.

**Comment by aliscott** [comment] 2022-05-23 14:23
@dyordsabuzo I'm closing this as a duplicate so we can track it as part of https://github.com/infracost/infracost/issues/1641, so please watch that for updates on a fix for this 🙏

**Closed by aliscott** 2022-05-23 14:23 UTC
Labels: bug
