### ISSUE TITLE
Infracost core dumps under atlantis 17.1 and 17.2 on some repos

### ISSUE THREAD

**Issue by endriu0** [infracost/infracost#852] opened 2021-07-02 11:09 UTC
Hey team, running into issue with infracost since upgrading to atlantis 17.1 / 17.2 - issue only appears on some plans. Not all - specifically I was able to find one application that causes it. Tried with all infracost 9.x versions.

After going back to atlantis 17.0 and infracost 9.0 issues are gone.

When trying to narrow it down it seems to be running into issues on this line in atlantis_diff :  https://github.com/infracost/infracost/blob/bfb09a19afa1f5b59e91ce6fc097ec505140b5bd/scripts/ci/atlantis_diff.sh#L155 

but running the same command directly in the atlantis pod seems to work with no issues.

Debug : 
```
time="2021-07-02T11:04:14Z" level=info msg="Detected Terraform plan file at /atlantis-data/repos/myorg/atlantis_test/11/default/infracost-test/default.tfplan"
time="2021-07-02T11:04:15Z" level=info msg="starting: Running terraform show"
time="2021-07-02T11:04:15Z" level=info msg="Running command: /usr/local/bin/terraform0.12.31 show -no-color -json default.tfplan"
time="2021-07-02T11:04:17Z" level=info msg="starting: Calculating monthly cost estimate"
Running infracost output using:
  $ infracost output --no-color --format diff --path infracost_breakdown.json
Posting comment as post_condition is set to has_diff and there is a diff
Segmentation fault (core dumped)
##### Infracost estimate #####

Monthly cost will increase by $1437

Previous monthly cost: $0.00
New monthly cost: $1437

Infracost output:
```

Running the infracost output directly works perfectly. It seems to be only failing when running from script. Afaik atlantis didn't make drastic changes from. 17.0 up to 17.2 to the way plans are outputed therefore am at loss what might be causing that.

**Comment by aliscott** [comment] 2021-07-02 11:48
I wonder if this could this be an out of memory issue if it's only happening in the pod. What is the size that of the `infracost_breakdown.json` it generates when it hits the issue?

**Comment by idan-gur** [comment] 2021-07-05 07:20
Also happens to me, would be glad for any help, doesn't seem to be a memory issue as my pod's peak memory isn't near full.

**Comment by endriu0** [comment] 2021-07-05 09:31
Sorry - just saw this - wouldn't say it's that big : 

```
-rw-r--r--    1 atlantis atlantis   26.3K Jul  2 11:04 infracost_breakdown.json
```

Also looking at the pod it doesn't do much - I was able to replicate it in our testing atlantis deployment which doesn't do anything 99% of the time.

**Comment by aliscott** [comment] 2021-07-05 10:24
Thanks @idan-gur and @endriu0 🙂  I've been able to reproduce this now so will investigate.

**Comment by aliscott** [comment] 2021-07-05 14:06
@idan-gur, @endriu0 I've pushed a fix in https://github.com/infracost/infracost/pull/855. It looks like it was an issue with the shell, not sure if this changed in the underlying Atlantis image or not.

I've also pushed this in the `infracost-atlantis:latest` Docker image. Note: this still uses Atlantis v0.17.0, but I've tested the fix with v0.17.2 as well.

Can you confirm this is now working for you?

**Comment by endriu0** [comment] 2021-07-05 14:23
Just tested - outputted correctly now. Thanks

**Comment by aliscott** [comment] 2021-07-05 14:32
Awesome, thanks for your help with this 🚀!

**Closed by aliscott** 2021-07-05 14:32 UTC
