### ISSUE TITLE
Infracost v0.10.0 Terragrunt panic: must not call MapVal with empty map (works on v0.9.24)

### ISSUE THREAD

**Issue by andrejskuidins** [infracost/infracost#1691] opened 2022-05-27 08:35 UTC
\\$ infracost breakdown --path=${TF_ROOT} \
                                       --format=json \
                                       --out-file=${TF_ROOT}/infracost.json
time="2022-05-27T08:16:49Z" level=info msg="Detected Terragrunt directory at /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure"
time="2022-05-27T08:16:50Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T08:16:50Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T08:16:50Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T08:16:50Z" level=info msg="Starting: Evaluating Terraform directory"
panic: must not call MapVal with empty map
goroutine 56 [running]:
github.com/zclconf/go-cty/cty.MapVal(0xc0003f6de0?)
	/home/runner/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/value_init.go:212 +0x4a5
github.com/infracost/infracost/internal/providers/terraform.(*TerragruntHCLProvider).fetchDependencyOutputs(0xc0003ba6f0, 0xc0002c4240)
	/home/runner/work/infracost/infracost/internal/providers/terraform/terragrunt_hcl_provider.go:316 +0x668
github.com/infracost/infracost/internal/providers/terraform.(*TerragruntHCLProvider).runTerragrunt(0xc0003ba6f0, 0xc0002c4240)
	/home/runner/work/infracost/infracost/internal/providers/terraform/terragrunt_hcl_provider.go:183 +0x65
github.com/infracost/infracost/internal/providers/terraform.(*TerragruntHCLProvider).prepWorkingDirs.func1(0xc00044[61](https://gitlab.com/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/-/jobs/2513741888#L61)50?)
	/home/runner/work/infracost/infracost/internal/providers/terraform/terragrunt_hcl_provider.go:141 +0x30
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runNow(0xc0007b3bd0)
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.9/configstack/running_module.go:239 +0x122
github.com/gruntwork-io/terragrunt/configstack.(*runningModule).runModuleWhenReady(0x0?, 0xc0007ed500)
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.9/configstack/running_module.go:202 +0x9a
github.com/gruntwork-io/terragrunt/configstack.runModules.func1(0x0?)
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.9/configstack/running_module.go:172 +0x58
created by github.com/gruntwork-io/terragrunt/configstack.runModules
	/home/runner/go/pkg/mod/github.com/gruntwork-io/terragrunt@v0.36.9/configstack/running_module.go:1[70](https://gitlab.com/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/-/jobs/2513741888#L70) +0x90
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by hugorut** [comment] 2022-05-27 09:17
Hey @andrejskuidins I'm closing this as it's a duplicate of https://github.com/infracost/infracost/issues/1641. We have a fix for this issue in a branch. It would be great if you could test it out and check if it fixes your issue. You can get it by running the following:

```
curl -o infracost-build https://infracost-public-dumps.s3.amazonaws.com/builds/2705/infracost-darwin-arm64
chmod +x ./infracost-build
./infracost-build breakdown --path=${TF_ROOT}
```

You'll need to replace `infracost-darwin-arm64` with whichever OS system you use. Valid binaries are:

```
infracost-arm64.exe
infracost-darwin-amd64
infracost-darwin-arm64
infracost-linux-amd64
infracost-linux-arm64
infracost.exe
```

**Closed by hugorut** 2022-05-27 09:17 UTC
Labels: bug

**Comment by andrejskuidins** [comment] 2022-05-27 10:30
Looks good, just trying to debug infracost comment gitlab command right now:
`$ infracost breakdown --path=${TF_ROOT} \ # collapsed multi-line command
time="2022-05-27T10:14:14Z" level=info msg="Detected Terragrunt directory at /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure"
time="2022-05-27T10:14:15Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T10:14:15Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T10:14:15Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T10:14:15Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T10:14:16Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T10:14:16Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T10:14:16Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-27T10:14:17Z" level=info msg="Output saved to /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/infracost.json"
$ infracost comment gitlab --path=${TF_ROOT}/infracost.json \ # collapsed multi-line command
Error: Error creating comment: 404 Not Found`

**Comment by alikhajeh1** [comment] 2022-05-27 14:41
@andrejskuidins any luck? I assume https://gitlab.com/infracost/infracost-gitlab-ci#troubleshooting didn't help?
Would it have helped you debug this if the CLI had output the HTTP request made to gitlab when `--log-level=debug`?

**Comment by andrejskuidins** [comment] 2022-05-27 14:57
@alikhajeh1 no luck for now:

$ infracost breakdown --path=${TF_ROOT} --format=json --out-file=${TF_ROOT}/infracost.json
time="2022-05-27T14:55:07Z" level=info msg="Detected Terragrunt directory at /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure"
time="2022-05-27T14:55:08Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T14:55:08Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T14:55:08Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T14:55:08Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T14:55:09Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T14:55:09Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T14:55:09Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-27T14:55:10Z" level=info msg="Output saved to /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/infracost.json"
$ echo ${TF_ROOT}/infracost.json
/builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/infracost.json
$ echo $CI_PROJECT_PATH
1nce-tech/miscellaneous/central-monitoring-dev-infrastructure
$ echo $CI_MERGE_REQUEST_IID
25
$ echo $GITLAB_TOKEN
[MASKED]
$ infracost comment gitlab --path ${TF_ROOT}/infracost.json --repo $CI_PROJECT_PATH --merge-request $CI_MERGE_REQUEST_IID --gitlab-token $GITLAB_TOKEN --behavior update --log-level=debug
time="2022-05-27T14:[55](https://gitlab.com/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/-/jobs/2515511771#L55):10Z" level=info msg="Finding matching comments for tag infracost-comment"
time="2022-05-27T14:55:10Z" level=info msg="Found 0 matching comments"
time="2022-05-27T14:55:10Z" level=info msg="Creating new comment"
Error: Error creating comment: 404 Not Found
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1

**Comment by alikhajeh1** [comment] 2022-05-27 15:05
@andrejskuidins hmm that 404 is odd, I assume you're using gitlab.com? otherwise you can add this:
```
--gitlab-server-url=$CI_SERVER_URL
```

**Comment by hugorut** [comment] 2022-05-27 15:06
@andrejskuidins are perchance using GitLab enterprise or self-managed? It might be that you need to add `--gitlab-server-url` with your server config

**Comment by hugorut** [comment] 2022-05-27 15:06
ahha @alikhajeh1 got in two quick!

**Comment by andrejskuidins** [comment] 2022-05-27 16:09
@alikhajeh1 @hugorut can you please chekc now?

\\$ infracost breakdown --path=${TF_ROOT} --format=json --out-file=\\${TF_ROOT}/infracost.json
time="2022-05-27T16:07:09Z" level=info msg="Detected Terragrunt directory at /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure"
time="2022-05-27T16:07:10Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T16:07:10Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T16:07:10Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T16:07:10Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T16:07:10Z" level=info msg="Starting: Downloading Terraform modules"
time="2022-05-27T16:07:10Z" level=info msg="Starting: Evaluating Terraform directory"
time="2022-05-27T16:07:11Z" level=info msg="Starting: Retrieving cloud prices to calculate costs"
time="2022-05-27T16:07:12Z" level=info msg="Output saved to /builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/infracost.json"
\\$ echo ${TF_ROOT}/infracost.json
/builds/1nce-tech/miscellaneous/central-monitoring-dev-infrastructure/infracost.json
\\$ echo $CI_PROJECT_PATH
1nce-tech/miscellaneous/central-monitoring-dev-infrastructure
\\$ echo $CI_MERGE_REQUEST_IID
25
$ echo $GITLAB_TOKEN
[MASKED]
\\$ echo $CI_SERVER_URL
https://gitlab.com/
\\$ infracost comment gitlab --path \\${TF_ROOT}/infracost.json --repo \\$CI_PROJECT_PATH --merge-request \\$CI_MERGE_REQUEST_IID --gitlab-token $GITLAB_TOKEN --behavior update --gitlab-server-url=$CI_SERVER_URL --log-level=debug
time="2022-05-27T16:07:12Z" level=info msg="Finding matching comments for tag infracost-comment"
time="2022-05-27T16:07:12Z" level=info msg="Found 0 matching comments"
time="2022-05-27T16:07:12Z" level=info msg="Creating new comment"
Error: Error creating comment: 404 Not Found
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 1

**Comment by alikhajeh1** [comment] 2022-05-27 18:32
@andrejskuidins the CLI does a curl like the following to post the comment, I noticed your `$CI_PROJECT_PATH` doesn't have my-org/my-repo format, as it has an extra `miscellaneous` word in it. Can you please try the following curls from your laptop with your token to see if any of them work?

```
curl -X POST --header "PRIVATE-TOKEN: abc" --data-urlencode "body=test1" https://gitlab.com/api/v4/projects/1nce-tech%2miscellaneous%2central-monitoring-dev-infrastructure/merge_requests/25/notes

curl -X POST --header "PRIVATE-TOKEN: abc" --data-urlencode "body=test2" https://gitlab.com/api/v4/projects/1nce-tech%2central-monitoring-dev-infrastructure/merge_requests/25/notes
```

Where:
- abc - is the value of the token
- test%2Frepo - should be your repo name in form namespace/project name with encoded slash character. 
- 123 is the number of the merge request (25 in your case)

**Comment by andrejskuidins** [comment] 2022-05-30 07:15
Good day @alikhajeh1 , that gives my two different errors:

my@linux:~/Documents$ curl -X POST --header "PRIVATE-TOKEN: superdupertoken" --data-urlencode "body=test1" https://gitlab.com/api/v4/projects/1nce-tech%2miscellaneous%2central-monitoring-dev-infrastructure/merge_requests/25/notes
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><\h1>400 Bad Request</h1></center>
<hr><center>cloudflare</center>
</body>
</html>

my@linux:~/Documents$ curl -X POST --header "PRIVATE-TOKEN: superdupertoken" --data-urlencode "body=test2" https://gitlab.com/api/v4/projects/1nce-tech%2central-monitoring-dev-infrastructure/merge_requests/25/notes
{"message":"404 Project Not Found"}

**Comment by andrejskuidins** [comment] 2022-05-30 09:44
Please disregard my latest comment, incorrect GITLAB TOKEN was used, thats why 404 error. But I would really appreciate if infracost outputs wil be little more informative :) 
💰 Infracost estimate: monthly cost will increase by $416 📈

**Comment by alikhajeh1** [comment] 2022-05-30 14:29
@andrejskuidins that's great, I've added https://github.com/infracost/infracost/issues/1693, feel free to add any ideas/comments to that issue with what else could have helped debug this.
