### ISSUE TITLE
Breakdown shows double charge for attached EBS volume

### ISSUE THREAD

**Issue by joshniec** [infracost/infracost#1143] opened 2021-11-22 15:48 UTC
Hello! I noticed that one of our workspaces declares an `aws_ebs_volume` resource, and an `aws_volume_attachment` resource that targets an `aws_instance` in the same file and when viewing the `infracost breakdown --path .`, a charge is shown for the invidual `aws_ebs_volume` as well as the `ebs_block_device[0]` when it is attached to the `aws_instance`. 

`infracost breakdown --path .`:
```
 aws_ebs_volume.storage
 └─ Storage (general purpose SSD, gp2)                             512  GB                   $51.20

 aws_instance.ec2
 ├─ Instance usage (Linux/UNIX, on-demand, t2.xlarge)              730  hours               $135.49
 ├─ root_block_device
 │  └─ Storage (general purpose SSD, gp2)                            8  GB                    $0.80
 └─ ebs_block_device[0]
    └─ Storage (general purpose SSD, gp2)                          512  GB                   $51.20
```

I'm not sure the right way to approach this (in terms of displaying the output correctly), such as if both should be included but set `ebs_block_device[0]`'s description to `Storage (attached aws_ebs_volume.storage)_   512 GB   $0.00*`. With a note at the bottom indicating that the asterisk means the line was added due to an attachment declaration to a resource? 

terraform code (note: I generalized some of the names and removed some other attributes from our original terraform code):
```
resource "aws_instance" "ec2" {
  ami           = "ami"
  instance_type = "t2.xlarge"

  root_block_device {
    delete_on_termination = true
    volume_size = 8 #GB
  }

  availability_zone = "us-east-1a"
}

resource "aws_ebs_volume" "storage" {
  availability_zone = "us-east-1a"
  size              = 512
  type              = "gp2"
}

resource "aws_volume_attachment" "storage_attachment" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.storage.id
  instance_id = aws_instance.ec2.id
}
```

**Comment by aliscott** [comment] 2021-11-22 16:03
Thanks @joshniec, this looks like a bug. I tried to reproduce but wasn't able to. I was using the following Terraform code:

```hcl
provider "aws" {
  region                      = "us-east-1" # <<<<< Try changing this to eu-west-1 to compare the costs
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  access_key                  = "mock_access_key"
  secret_key                  = "mock_secret_key"
}

resource "aws_instance" "ec2" {
  ami           = "ami"
  instance_type = "t2.xlarge"

  root_block_device {
    delete_on_termination = true
    volume_size = 8 #GB
  }

  availability_zone = "us-east-1a"
}

resource "aws_ebs_volume" "storage" {
  availability_zone = "us-east-1a"
  size              = 512
  type              = "gp2"
}

resource "aws_volume_attachment" "storage_attachment" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.storage.id
  instance_id = aws_instance.ec2.id
}
```

And got this output:

```
 Name                                                  Monthly Qty  Unit   Monthly Cost

 aws_ebs_volume.storage
 └─ Storage (general purpose SSD, gp2)                         512  GB           $51.20

 aws_instance.ec2
 ├─ Instance usage (Linux/UNIX, on-demand, t2.xlarge)          730  hours       $135.49
 └─ root_block_device
    └─ Storage (general purpose SSD, gp2)                        8  GB            $0.80

 OVERALL TOTAL                                                                  $187.49
──────────────────────────────────
3 cloud resources were detected, rerun with --show-skipped to see details:
∙ 2 were estimated, 2 include usage-based costs, see https://infracost.io/usage-file
∙ 1 was free
```

I wonder if this is happening only once the volume and instance are deployed? Can you confirm if you have run `terraform apply` before seeing this?

> I'm not sure the right way to approach this (in terms of displaying the output correctly), such as if both should be included but set ebs_block_device[0]'s description to Storage (attached aws_ebs_volume.storage)_ 512 GB $0.00*. With a note at the bottom indicating that the asterisk means the line was added due to an attachment declaration to a resource?

The intention at the moment is to just show it against the `aws_ebs_volume`, but having some way of indicating the attachment relationship in the output is a good idea.

**Comment by joshniec** [comment] 2021-11-22 16:08
> I wonder if this is happening only once the volume and instance are deployed? Can you confirm if you have run terraform apply before seeing this?

Yes, this code was already applied (I just came across the `infracost` tool and was running it in some of our directories to check it out). I can test and undeployed code, then deploy the cost and see if your suspicions are correct, then report back.

**Comment by joshniec** [comment] 2021-11-22 16:37
If I use the `--terraform-use-state` flag, I don't get the duplicate ebs volume (see end of comment for output example). I'm starting to think that maybe this isn't a bug and since the infrastructure & state already existed, I should have included the use of `--terraform-use-state` from the beginning. Thoughts? 

My code (for testing/reproducing):
```
# ec2.tf
resource "aws_instance" "ec2" {
  ami = "ami-0ff8a91507f77f867"
  instance_type = "t2.nano"
  subnet_id = "subnet-ID"

  root_block_device {
    delete_on_termination = true
    volume_size = 8
  }

  availability_zone = "us-east-1a"
}

resource "aws_ebs_volume" "storage" {
  availability_zone = "us-east-1a"
  size              = 128
  type              = "gp2"
}

resource "aws_volume_attachment" "storage_attachment" {
  device_name = "/dev/sdf"
  volume_id   = aws_ebs_volume.storage.id

```

terraform plan output:
```
Terraform will perform the following actions:

  # aws_ebs_volume.storage will be created
  + resource "aws_ebs_volume" "storage" {
      + arn               = (known after apply)
      + availability_zone = "us-east-1a"
      + encrypted         = (known after apply)
      + id                = (known after apply)
      + iops              = (known after apply)
      + kms_key_id        = (known after apply)
      + size              = 128
      + snapshot_id       = (known after apply)
      + tags_all          = (known after apply)
      + throughput        = (known after apply)
      + type              = "gp2"
    }

  # aws_instance.ec2 will be created
  + resource "aws_instance" "ec2" {
      + ami                                  = "ami-0ff8a91507f77f867"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = "us-east-1a"
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.nano"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = (known after apply)
      + tags_all                             = (known after apply)
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = true
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 8
          + volume_type           = (known after apply)
        }
    }

  # aws_volume_attachment.storage_attachment will be created
  + resource "aws_volume_attachment" "storage_attachment" {
      + device_name = "/dev/sdf"
      + id          = (known after apply)
      + instance_id = (known after apply)
      + volume_id   = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.
```

**infracost output, prior to terraform apply:**
```
Detected Terraform directory at .
  ✔ Checking for cached plan... change detected
  ✔ Running terraform plan
  ✔ Running terraform show

✔ Calculating monthly cost estimate

Project: .

 Name                                                 Monthly Qty  Unit   Monthly Cost

 aws_ebs_volume.storage
 └─ Storage (general purpose SSD, gp2)                        128  GB           $12.80

 aws_instance.ec2
 ├─ Instance usage (Linux/UNIX, on-demand, t4g.nano)          730  hours         $3.07
 └─ root_block_device
    └─ Storage (general purpose SSD, gp2)                       8  GB            $0.80

 OVERALL TOTAL                                                                  $16.67
──────────────────────────────────
3 cloud resources were detected, rerun with --show-skipped to see details:
∙ 2 were estimated, 2 include usage-based costs, see https://infracost.io/usage-file
∙ 1 was free
```

**infracost breakdown AFTER terraform applying above output:**
```
Detected Terraform directory at .
  ✔ Checking for cached plan... change detected
  ✔ Running terraform plan
  ✔ Running terraform show

✔ Calculating monthly cost estimate

Project: .

 Name                                                Monthly Qty  Unit   Monthly Cost

 aws_ebs_volume.storage
 └─ Storage (general purpose SSD, gp2)                       128  GB           $12.80

 aws_instance.ec2
 ├─ Instance usage (Linux/UNIX, on-demand, t2.nano)          730  hours         $4.23
 ├─ root_block_device
 │  └─ Storage (general purpose SSD, gp2)                      8  GB            $0.80
 └─ ebs_block_device[0]
    └─ Storage (general purpose SSD, gp2)                    128  GB           $12.80

 OVERALL TOTAL                                                                 $30.63
──────────────────────────────────
3 cloud resources were detected, rerun with --show-skipped to see details:
∙ 2 were estimated, 2 include usage-based costs, see https://infracost.io/usage-file
∙ 1 was free
```

If I use the `--terraform-use-state` flag, it doesn't show a duplicate though (which I probably should have used in the first place since everything is existing state):
```
Detected Terraform directory at .
  ✔ Running terraform show

✔ Calculating monthly cost estimate

Project: .

 Name                                                Monthly Qty  Unit   Monthly Cost

 aws_ebs_volume.storage
 └─ Storage (general purpose SSD, gp2)                       128  GB           $12.80

 aws_instance.ec2
 ├─ Instance usage (Linux/UNIX, on-demand, t2.nano)          730  hours         $4.23
 └─ root_block_device
    └─ Storage (general purpose SSD, gp2)                      8  GB            $0.80

 OVERALL TOTAL                                                                 $17.83
──────────────────────────────────
3 cloud resources were detected, rerun with --show-skipped to see details:
∙ 2 were estimated, 2 include usage-based costs, see https://infracost.io/usage-file
∙ 1 was free
```

**Comment by aliscott** [comment] 2021-11-22 16:43
Thanks for investigating @joshniec! This still seems like a bug to me. We would expect this to work both with and without `--terraform-use-state`, so it works if you're changing other parts of your Terraform project. I'll launch this on our test AWS account and dig into the Terraform plan file it produces a bit more to see what the issue is.

**Comment by aliscott** [comment] 2021-11-22 18:33
Thanks for the detailed report on this @joshniec. I've fixed the issue in https://github.com/infracost/infracost/pull/1145, so this fix will be in the next release (v0.9.14) which we are aiming to release later this week.

**Comment by joshniec** [comment] 2021-11-22 18:34
Thanks! I'll be on the look out. Sorry I would have debugged it myself and put up a PR if I felt a bit more comfortable with Go, not quite there yet :)

**Comment by aliscott** [comment] 2021-11-22 18:39
Great! If you're up for it any time we tag issues with "good first issue" that should help you get your feet wet.

**Comment by tim775** [comment] 2021-11-29 18:16
@joshniec this is live in v0.9.14, thanks for the write up!

**Closed by tim775** 2021-11-29 18:16 UTC
Labels: bug
