### ISSUE TITLE
Infracost show wrong estimate for vpc endpoints

### ISSUE THREAD

**Issue by khavishbhundoo** [infracost/infracost#2673] opened 2023-09-24 11:37 UTC
The pricing should be per month but infracost is showing the pricing for 1460 hours instead

![image](https://github.com/infracost/infracost/assets/18513761/890f3289-4b22-40ab-b6e7-d66f7d21876f)

**Comment by hugorut** [comment] 2023-09-25 08:23
@khavishbhundoo, thank you for bringing this to our attention. By default, Infracost displays all costs as "hourly" units, even though they represent the "monthly" costs. To clarify, in the example you provided, the hourly unit is indicative of the cost for using 2 VPC endpoint interfaces over the course of an entire month. To break it down, 1 month is equivalent to 730 hours, so for 2 endpoints, the total is 1460 hours. We opt to display most costs in hourly units because this is typically how AWS bills, which I believe holds true for VPC endpoints as well. For more information, you can refer to AWS's pricing page here: https://aws.amazon.com/privatelink/pricing/?nc1=h_ls. Please note the section **Pricing per VPC endpoint per AZ ($/hour)**. I'm closing this issue now, as it appears to align with expected behavior.

**Closed by hugorut** 2023-09-25 08:23 UTC

**Comment by khavishbhundoo** [comment] 2023-09-25 12:12
@hugorut I missed the per AZ part, i have 2 AZ so it makes sense that the cost is doubled
