### ISSUE TITLE
Please compile for darwin arm64

### ISSUE THREAD

**Issue by ameeno** [infracost/infracost#443] opened 2021-02-18 08:16 UTC
yea, I know it's really annoying.

Mac m1 and all that, and perhaps I could build it myself (have not really read)

it was a tough cookie to get terraform to work and providers had to be built manually for darwin_arm64

but there we go, new architecture and all that.

Would it be possible for you to release an arm64 darwin build? and perhaps even an arm64 Linux/windows build, cos why not eh?

**Comment by ameeno** [comment] 2021-02-18 08:18
NVM.
 Homebrew already installed an arm64 version for me, aren't them guys nice? :)

**Comment by alikhajeh1** [comment] 2021-02-18 08:41
Thanks for the heads-up @ameeno! Going to close this issue as it's a duplicate of https://github.com/infracost/infracost/issues/428, now that Go 1.16 is released I've added it to the [Todo list](https://github.com/infracost/infracost/projects/2). Homebrew folks are indeed very nice!

**Closed by alikhajeh1** 2021-02-18 08:41 UTC
