### ISSUE TITLE
GKE Cost is not well managed

### ISSUE THREAD

**Issue by dipakkumarsingh-atos** [infracost/infracost#1969] opened 2022-08-13 16:59 UTC
I have tried the GKE cost and it seems that from terraform module its not able to predict the cost for node pool. We are only able to see that there is a cluster management fee. But it's not showing if we have 1 node pool with 3 vm how much will it cost. 

Below is the code snippet you can use it

```hcl
resource "google_container_cluster" "primary" {
  provider   = google-beta
  name       = var.cluster_name
  location   = var.zone
  network    = var.network
  subnetwork = var.subnetwork

  depends_on = [
    google_compute_subnetwork.network-with-private-secondary-ip-ranges,
    google_compute_network.custom-vpc

  ]

  remove_default_node_pool = var.remove_default_node_pool
  initial_node_count       = var.initial_node_count

  release_channel {
    channel = var.type_release_channel
  }

  resource_labels = {
    "env"         = "production"
    "servicemesh" = "istio"
  }

  private_cluster_config {
    enable_private_endpoint = false
    enable_private_nodes    = true
    master_ipv4_cidr_block  = var.master_ipv4_cidr_block
  }

  ip_allocation_policy {
    cluster_secondary_range_name  = var.cluster_secondary_range_name
    services_secondary_range_name = var.services_secondary_range_name
  }

  enable_shielded_nodes = true

  vertical_pod_autoscaling {
    enabled = true
  }

  timeouts {
    create = "30m"
    update = "40m"
  }
}

resource "google_container_node_pool" "primary_nodes" {
  name              = var.node_pool_name
  location          = var.node_pool_location
  cluster           = google_container_cluster.primary.name
  node_count        = var.node_pool_node_count
  max_pods_per_node = var.node_pool_max_pods_per_node

  autoscaling {
    min_node_count = var.node_pool_min_node_count
    max_node_count = var.node_pool_max_node_count
  }

  node_config {
    service_account = var.service_account
    preemptible     = var.node_config_preemptible
    disk_size_gb    = var.node_config_disk_size_gb
    disk_type       = var.node_config_disk_type
    image_type      = var.node_config_image_type
    machine_type    = var.node_config_machine_type
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }
  }
}
```

**Comment by KelvinVenancio** [comment] 2022-08-26 13:31
Same behavior here by using the [GKE Module](https://registry.terraform.io/modules/terraform-google-modules/kubernetes-engine/google/latest).

**Comment by aliscott** [comment] 2022-12-05 12:58
@dipakkumarsingh-atos do you have examples of how you are defining the following variables?
* `initial_node_count`
* `node_pool_node_count`
* `node_pool_min_node_count`

I've tried with the above code, adding in some variable values ([see this gist](https://gist.github.com/aliscott/99e5b8c6b4174cb2ab99fa1639acd81a)), but I'm unable to reproduce the issue.

**Comment by aliscott** [comment] 2022-12-12 12:49
@dipakkumarsingh-atos, @KelvinVenancio, @jonchen727 I'm closing this since I've been unable to reproduce. If you have a reproducible example please reopen this and we will look into it 🙏

**Closed by aliscott** 2022-12-12 12:49 UTC
Labels: bug, google
